#pragma once

#include "GameplayTagContainer.h"
#include "Data/BehaviorEvaluatorDataTypes.h"
#include "BehaviorEvaluatorOperations_DataTypes.generated.h"

UENUM(BlueprintType)
enum class EBehaviorEvaluatorOperationType : uint8
{
	None,
	Add,
	Multiply,
	Divide,
	Subtract,
	Power,
};

USTRUCT(BlueprintType)
struct FGameplayTagFilterScalarValue
{
	GENERATED_BODY()
	
public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly)
	FGameplayTagQuery Filter;
	
	UPROPERTY(EditAnywhere, BlueprintReadOnly)
	float Value = 1.f; 
};

USTRUCT(BlueprintType)
struct FActorInterestCondition
{
	GENERATED_BODY()
	
	UPROPERTY(EditAnywhere, BlueprintReadOnly)
	FGameplayTagQuery TagsQuery;
	
	// Interest is valid only if target attitude is among these attitudes OR this container is empty
	UPROPERTY(EditAnywhere, BlueprintReadOnly)
	FGameplayTagContainer RelevantAttitudes;
	
	// will be put in behavior tags in BB
	UPROPERTY(EditAnywhere, BlueprintReadOnly)
	FGameplayTag InterestCause;

	UPROPERTY(EditAnywhere, BlueprintReadOnly)
	float ScoreScale = 1.f;
};

struct FOperationContextBase
{
	TWeakObjectPtr<APawn> Pawn;
	float Health = 0.f;
	float MaxHealth = 1.f;
	float ActiveBehaviorDuration = 0.f; // for fight/retreat this means how long is the state active 
	
	// 22 Apr 2026 (aki): бляяяяяяяяяяять какой же я гондон 
	mutable float AccumulatedScore = 0.f;
	mutable TMap<FName, float> CachedVariables;
	
	EBehaviorEvaluatorState EvaluatorState;
};

struct FRelativeOperationContext : public FOperationContextBase
{
};

struct FAggregationOperationContext : public FOperationContextBase
{
	FGameplayTagContainer Tags;
};

USTRUCT(BlueprintType)
struct FBehavorEvaluatorOperationsContainerBase
{
	GENERATED_BODY()
	
public:
	virtual ~FBehavorEvaluatorOperationsContainerBase() = default;
	
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, meta=(MultiLine=true))
	FString AutoGeneratedFormula;
	
	// it doesnt limit amount of stored variables, it just allocates them in advance to prevent frequent memory allocations
	UPROPERTY(EditAnywhere, BlueprintReadOnly, meta=(UIMin = 0, ClampMin = 0))
	int ReservedVariables = 0;
	
	virtual void GenerateFormulaDescription() {};
};
