#pragma once

#include "CoreMinimal.h"
#include "BehaviorEvaluators/BehaviorEvaluator_Base.h"
#include "BehaviorEvaluators/Operations/BehaviorEvaluatorOperations_Aggregating.h"
#include "BehaviorEvaluators/Operations/BehaviorEvaluatorOperations_Relative.h"
#include "BehaviorEvaluator_OperationBased.generated.h"

bool IsDetectable(EDetectionSource DetectionSource);

USTRUCT(BlueprintType)
struct FEntityOperationEvaluationParameters
{
	GENERATED_BODY()
	
	// Deprecated
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	FGameplayTagQuery EntityRelevantQuery;
	
	// These operations affect both utility AND priority
	UPROPERTY(EditAnywhere, BlueprintReadOnly)
	FBehavorEvaluatorRelativeOperationsContainer IndividualUtilityOperationsContainer;
	
	// These operations affect ONLY priority and act as appendix to priority when utility must remain the same. 
	// For example: "is current target?". It must affect only priority, but not utility
	UPROPERTY(EditAnywhere, BlueprintReadOnly)
	FBehavorEvaluatorRelativeOperationsContainer IndividualPriorityOperationsContainer;
	
	UPROPERTY(EditAnywhere, BlueprintReadOnly, meta=(ExcludeBaseStruct))
	TInstancedStruct<FBehaviorEvaluatorOperationCondition_Base> RelevancyCondition;
	
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, meta=(MultiLine=true))
	FString AutoGeneratedConditionsFormula;
	
	// prevents NPCs from chasing packs of rats (or whatever low-value enemies)
	UPROPERTY(EditAnywhere, BlueprintReadOnly)
	FRuntimeFloatCurve EntityOrderedScoreScale;
	
	UPROPERTY(EditAnywhere, BlueprintReadOnly)
	FRuntimeFloatCurve EntityPressureSaturationCurve;
	
	UPROPERTY(EditAnywhere, BlueprintReadOnly)
	FString DebugInfo = "";
};

UCLASS(meta=(Hidden))
class ARPGAI_API UBehaviorEvaluatorConfig_OperationBased : public UBehaviorEvaluatorConfig_Base
{
	GENERATED_BODY()

public:
	virtual void GenerateFormulasDescriptions();
	
	UPROPERTY(EditAnywhere, BlueprintReadOnly)
	FBehavorEvaluatorAggregatingOperationsContainer StatePressureOperationsContainer;
	
	UPROPERTY(EditAnywhere, BlueprintReadOnly)
	FRuntimeFloatCurve StatePressureSaturationCurve;

	UPROPERTY(EditAnywhere, BlueprintReadOnly)
	FEntityOperationEvaluationParameters EnemiesEvaluationParameters;
};

class FBehaviorEvaluator_OperationBased : public FBehaviorEvaluator_Base
{
private:
	using Super = FBehaviorEvaluator_Base;
	
protected:
	
	struct FBehaviorEvaluator_ActorScore
	{
		AActor* Actor = nullptr;
		float UtilityScore = 0.f;
		float PriorityScore = 0.f;
		EDetectionSource DetectionSource = EDetectionSource::None;
		bool bAlive = true;
		
		bool operator < (const FBehaviorEvaluator_ActorScore& Other) const
		{
			// const float ThisKnowsLocationScale = IsDetectable(DetectionSource) ? 10.f : 0.f;
			// const float OtherKnowsLocationScale = IsDetectable(Other.DetectionSource) ? 10.f : 0.f;
			// const float ThisAliveScale = bAlive ? 1.f : 0.1f;
			// const float OtherAliveScale = Other.bAlive ? 1.f : 0.1f;
			// return UtilityScore * ThisKnowsLocationScale * ThisAliveScale > Other.UtilityScore * OtherKnowsLocationScale * OtherAliveScale;
			return (UtilityScore + PriorityScore) > (Other.UtilityScore + Other.PriorityScore);
		}
	};
	
	using FActorScoresContainer = TArray<FBehaviorEvaluator_ActorScore, TInlineAllocator<8>>;
	using FOperationsContainer = TArray<TInstancedStruct<FBehaviorEvaluatorOperation_Relative_Base>>;
	
public:
	FBehaviorEvaluator_OperationBased(UBehaviorTreeComponent& OwnerComp, const UBehaviorEvaluatorConfig_Base* Config);

protected:
	virtual void Update(const float DeltaTime) override;
	FAggregationOperationContext GetAggregationOperationContext() const;
	FRelativeOperationContext GetRelativeOperationContext() const;
	virtual float Evaluate();
	float CalculateStatePressure() const;
	
	virtual bool IsCharacterRelevant(const FRelativeOperationContext& Context,
	                                 const FEntityOperationEvaluationParameters& EvaluationParameters, const FCharacterShortTermMemory& CharacterSTM, AActor* Character) const;
	virtual void OnIndividualScoreCalculated(AActor* Actor, const FCharacterShortTermMemory& Value, float IndividualScore) {};
	virtual void PreEvaluate() {};

	void ExecuteEntityOperations(AActor* Target, const FCharacterShortTermMemory& CharacterSTM,
	                             const FRelativeOperationContext& RelativeOperationData, FActorScoresContainer& Container,
	                             const FEntityOperationEvaluationParameters& EvaluationParameters);
	float GetEntitiesAggregatedScore(FActorScoresContainer& ActorScores, const FEntityOperationEvaluationParameters& EvaluationParameters) const;
	
	TWeakObjectPtr<const UBehaviorEvaluatorConfig_OperationBased> OperationsConfig;
	
private:
	float Health = 0.f;
	float MaxHealth = 0.f;
};
