#include "BehaviorEvaluators/v2/BehaviorEvaluator_OperationBased.h"

#include "AIController.h"
#include "Components/Controller/NpcPerceptionComponent.h"
#include "BehaviorEvaluators/Operations/BehaviorEvaluatorOperations_Conditions.h"
#include "Data/LogChannels.h"
#include "Interfaces/Npc.h"
#include "Interfaces/NpcActorTagsInterface.h"
#include "Interfaces/NpcAliveActor.h"

void UBehaviorEvaluatorConfig_OperationBased::GenerateFormulasDescriptions()
{
	StatePressureOperationsContainer.GenerateFormulaDescription();
	EnemiesEvaluationParameters.IndividualUtilityOperationsContainer.GenerateFormulaDescription();
	EnemiesEvaluationParameters.IndividualPriorityOperationsContainer.GenerateFormulaDescription();
	if (EnemiesEvaluationParameters.RelevancyCondition.IsValid())
		EnemiesEvaluationParameters.AutoGeneratedConditionsFormula = EnemiesEvaluationParameters.RelevancyCondition.Get().ToString(0);
	else
		EnemiesEvaluationParameters.AutoGeneratedConditionsFormula = "";
}

FBehaviorEvaluator_OperationBased::FBehaviorEvaluator_OperationBased(UBehaviorTreeComponent& OwnerComp,
                                                                     const UBehaviorEvaluatorConfig_Base* Config) : Super(OwnerComp, Config)
{
	OperationsConfig = Cast<UBehaviorEvaluatorConfig_OperationBased>(Config);
	Health = 0.f;
	MaxHealth = 0.f;
}

void FBehaviorEvaluator_OperationBased::Update(const float DeltaTime)
{
	Super::Update(DeltaTime);
	auto AliveCreatureInterface = Cast<INpcAliveActor>(Pawn.Get());
	Health = AliveCreatureInterface->GetHealth_NPC();
	MaxHealth = AliveCreatureInterface->GetMaxHealth_NPC();
	
	const float RegressionOffset = GetUtilityOffset();
	const float BehaviorUtility = Evaluate();
	UE_CVLOG(BaseConfig->bLogEnabled, AIController.Get(), LogARPGAI_BE, Verbose, TEXT("Delta utility raw = %.2f + %.2f = %.2f"),
		RegressionOffset, BehaviorUtility, RegressionOffset + BehaviorUtility);
	InterpolateUtility(RegressionOffset + BehaviorUtility, DeltaTime);
}

float FBehaviorEvaluator_OperationBased::Evaluate()
{
	PreEvaluate();
	return 0.f;
}

FRelativeOperationContext FBehaviorEvaluator_OperationBased::GetRelativeOperationContext() const
{
	FRelativeOperationContext RelativeOperationContext;
	RelativeOperationContext.Pawn = Pawn;
	RelativeOperationContext.Health = Health;
	RelativeOperationContext.MaxHealth = MaxHealth;
	RelativeOperationContext.EvaluatorState = GetState();
	RelativeOperationContext.bLogEnabled = BaseConfig->bLogEnabled;
	if (GetState() == EBehaviorEvaluatorState::Activated)
		RelativeOperationContext.ActiveBehaviorDuration = Pawn->GetWorld()->GetTimeSeconds() - BehaviorStartTime;
	
	return RelativeOperationContext;
}

FAggregationOperationContext FBehaviorEvaluator_OperationBased::GetAggregationOperationContext() const
{
	FAggregationOperationContext AggregationOperationContext;
	AggregationOperationContext.Pawn = Pawn;
	AggregationOperationContext.Health = Health;
	AggregationOperationContext.MaxHealth = MaxHealth;
	AggregationOperationContext.EvaluatorState = GetState();
	AggregationOperationContext.bLogEnabled = BaseConfig->bLogEnabled;
	
	if (GetState() == EBehaviorEvaluatorState::Activated)
		AggregationOperationContext.ActiveBehaviorDuration = Pawn->GetWorld()->GetTimeSeconds() - BehaviorStartTime;
	
	if (auto TagsInterface = Cast<INpcActorTagsInterface>(Pawn))
		AggregationOperationContext.Tags = TagsInterface->GetTags_NPC();
	
	return AggregationOperationContext;
}

float FBehaviorEvaluator_OperationBased::CalculateStatePressure() const
{
	TRACE_CPUPROFILER_EVENT_SCOPE(FBehaviorEvaluator_OperationBased::CalculateStatePressure)
	
	float RawStatePressure = 0.f;
	FAggregationOperationContext AggregationOperationData = GetAggregationOperationContext();
	for (const auto& OperationIS : OperationsConfig->StatePressureOperationsContainer.Operations)
	{
		if (!ensure(OperationIS.IsValid()))
			continue;
		
		const auto& Operation = OperationIS.Get();
		RawStatePressure = Operation.Evaluate(AggregationOperationData, PerceptionComponent.Get(), RawStatePressure);
		UE_CVLOG(BaseConfig->bLogEnabled, AIController.Get(), LogARPGAI_BE, VeryVerbose, TEXT("Aggregative state pressure after [%s] = %.2f"),
				*Operation.GetShortDescription(), RawStatePressure);
	}

	float SaturatedStateScore = OperationsConfig->StatePressureSaturationCurve.GetRichCurveConst()->Eval(RawStatePressure);
	UE_CVLOG(BaseConfig->bLogEnabled, AIController.Get(), LogARPGAI_BE, Verbose, TEXT("Raw state pressure = %.2f"), RawStatePressure);
	UE_CVLOG(BaseConfig->bLogEnabled, AIController.Get(), LogARPGAI_BE, Verbose, TEXT("Saturated state pressure = %.2f"), SaturatedStateScore);
	
	return SaturatedStateScore;
}

bool FBehaviorEvaluator_OperationBased::IsCharacterRelevant(const FRelativeOperationContext& Context,
	const FEntityOperationEvaluationParameters& EvaluationParameters, const FCharacterShortTermMemory& CharacterSTM, AActor* Character) const
{
	TRACE_CPUPROFILER_EVENT_SCOPE(FBehaviorEvaluator_OperationBased::IsCharacterRelevant)
	
	if (EvaluationParameters.RelevancyCondition.IsValid())
		return EvaluationParameters.RelevancyCondition.Get().Evaluate(Context, Character, CharacterSTM);

	return true;
	
	// return EvaluationParameters.EntityRelevantQuery.IsEmpty() || EvaluationParameters.EntityRelevantQuery.Matches(CharacterSTM.CharacterTags);
}

void FBehaviorEvaluator_OperationBased::ExecuteEntityOperations(AActor* Target, const FCharacterShortTermMemory& CharacterSTM,
                                                                const FRelativeOperationContext& RelativeOperationData, FActorScoresContainer& Container,
                                                                const FEntityOperationEvaluationParameters& EvaluationParameters)
{
	if (!IsCharacterRelevant(RelativeOperationData, EvaluationParameters, CharacterSTM, Target))
	{
		UE_CVLOG(BaseConfig->bLogEnabled, AIController.Get(), LogARPGAI_BE, Verbose, TEXT("[%s] %s is irrelevant"),
			*EvaluationParameters.DebugInfo, *CharacterSTM.CharacterId.ToString());
		return;
	}

	{
		
	TRACE_CPUPROFILER_EVENT_SCOPE(FBehaviorEvaluator_OperationBased::ExecuteEntityOperations)
	
	float IndividualUtilityScore = 0.f;
	UE_CVLOG(BaseConfig->bLogEnabled, AIController.Get(), LogARPGAI_BE, Verbose, TEXT("Calculating individual utility score for %s"),
		*CharacterSTM.CharacterId.ToString());
	for (const auto& OperationIS : EvaluationParameters.IndividualUtilityOperationsContainer.Operations)
	{
		if (!ensure(OperationIS.IsValid()))
			continue;
				
		const auto& Operation = OperationIS.Get();
		if (!Operation.IsEnabled())
			continue;
		
		IndividualUtilityScore = Operation.Evaluate(RelativeOperationData, Target, CharacterSTM, IndividualUtilityScore);
		UE_CVLOG(BaseConfig->bLogEnabled, AIController.Get(), LogARPGAI_BE, VeryVerbose, TEXT("Utility score after [%s] = %.2f"),
			*Operation.GetShortDescription(), IndividualUtilityScore);
	}
	
	float IndividualPriorityScore = 0.f;
	if (GetState() == EBehaviorEvaluatorState::Activated)
	{
		UE_CVLOG(BaseConfig->bLogEnabled, AIController.Get(), LogARPGAI_BE, Verbose, TEXT("Calculating individual priority score for %s"),
		*CharacterSTM.CharacterId.ToString());
		for (const auto& OperationIS : EvaluationParameters.IndividualPriorityOperationsContainer.Operations)
		{
			if (!ensure(OperationIS.IsValid()))
				continue;
				
			const auto& Operation = OperationIS.Get();
			if (!Operation.IsEnabled())
				continue;
		
			IndividualPriorityScore = Operation.Evaluate(RelativeOperationData, Target, CharacterSTM, IndividualPriorityScore);
			UE_CVLOG(BaseConfig->bLogEnabled, AIController.Get(), LogARPGAI_BE, VeryVerbose, TEXT("Priority after [%s] = %.2f"),
				*Operation.GetShortDescription(), IndividualPriorityScore);
		}
	}
	
	FBehaviorEvaluator_ActorScore ActorScore = FBehaviorEvaluator_ActorScore(Target, IndividualUtilityScore,
		IndividualPriorityScore, CharacterSTM.DetectionSource, CharacterSTM.bAlive);
	
	Container.Add(ActorScore);
	OnIndividualScoreCalculated(Target, CharacterSTM, IndividualUtilityScore);
	
#if WITH_EDITOR
	UE_CVLOG(BaseConfig->bLogEnabled, AIController.Get(), LogARPGAI_BE, Verbose, TEXT("Individual utility score for %s = %.2f"),
		*CharacterSTM.CharacterId.ToString(), IndividualUtilityScore);
	UE_CVLOG(BaseConfig->bLogEnabled, AIController.Get(), LogARPGAI_BE, Verbose, TEXT("Individual priority score for %s = %.2f"),
		*CharacterSTM.CharacterId.ToString(), IndividualPriorityScore);
	UE_CVLOG_CAPSULE(BaseConfig->bLogEnabled, AIController.Get(), LogARPGAI_BE, Verbose, Target->GetActorLocation() - FVector::UpVector * 90.f,
		90.f, 30.f, FQuat::Identity, FColorList::Turquoise, TEXT("Individual score = %.2f"), IndividualUtilityScore);
#endif
	}
}

float FBehaviorEvaluator_OperationBased::GetEntitiesAggregatedScore(FActorScoresContainer& ActorScores,
	const FEntityOperationEvaluationParameters& EvaluationParameters) const
{
	if (ActorScores.IsEmpty())
	{
		UE_CVLOG(BaseConfig->bLogEnabled, AIController.Get(), LogARPGAI_BE, Verbose, TEXT("No entities for [%s] -> entity evaluation = 0.f"), *EvaluationParameters.DebugInfo);
		return 0.f;
	}
	
	float RawResult = 0.f;
	const auto* OrderScaleCurve = EvaluationParameters.EntityOrderedScoreScale.GetRichCurveConst();
	ActorScores.Sort();
	for (int i = 0; i < ActorScores.Num(); ++i)
	{
		ActorScores[i].UtilityScore *= OrderScaleCurve->Eval(i);
		RawResult += ActorScores[i].UtilityScore;
	}

	const float SaturatedScore = EvaluationParameters.EntityPressureSaturationCurve.GetRichCurveConst()->Eval(RawResult);
	
	UE_CVLOG(BaseConfig->bLogEnabled, AIController.Get(), LogARPGAI_BE, Verbose, TEXT("Raw score for [%s] = %.2f"), *EvaluationParameters.DebugInfo, RawResult);
	UE_CVLOG(BaseConfig->bLogEnabled, AIController.Get(), LogARPGAI_BE, Verbose, TEXT("Saturated score for [%s] = %.2f"), *EvaluationParameters.DebugInfo, SaturatedScore);
	return SaturatedScore;
}
